"""initial

Revision ID: 91767e5bdc65
Revises: 
Create Date: 2026-04-25 12:34:22.336937+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91767e5bdc65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('entry_lat', sa.Float(), nullable=True),
    sa.Column('entry_lng', sa.Float(), nullable=True),
    sa.Column('total_bays', sa.Integer(), nullable=False),
    sa.Column('floor_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bays',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('structure_id', sa.String(), nullable=False),
    sa.Column('bay_number', sa.String(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('bay_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('structure_id', sa.String(), nullable=False),
    sa.Column('entry_gate', sa.Integer(), nullable=False),
    sa.Column('exit_gate', sa.Integer(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('duration_mins', sa.Integer(), nullable=True),
    sa.Column('assigned_zone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('device_hash', sa.String(), nullable=True),
    sa.Column('parked_bay_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parked_bay_id'], ['bays.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_batches')
    op.drop_table('sessions')
    op.drop_table('bays')
    op.drop_table('structures')
    # ### end Alembic commands ###
